### ISSUE TITLE
Wiki Home Page

### ISSUE THREAD

**Issue by aycelacap** [darianchen/Syntax-Error#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

**Comment by aycelacap** [comment]
Hi Darian. Ensure you have a placeholder link! https://stackoverflow.com/ can work for now!

**Comment by darianchen** [comment]
Hey Ayce, I added the placeholder link. Also all the other issues closed by themselves, does that mean there is nothing wrong with my schema, frontend routes etc...?

**Comment by aycelacap** [comment]
Yes, so far your docs look great. I will make some suggestions along the way but all of the docs are on point!

**Comment by aycelacap** [comment]
I just left a comment on the sample state
